export enum Projectile {
  arrow = 'minecraft:arrow',
  dragonFireball = 'minecraft:dragon_fireball',
  egg = 'minecraft:egg',
  enderPearl = 'minecraft:ender_pearl',
  experienceBottle = 'minecraft:experience_bottle',
  eyeOfEnder = 'minecraft:eye_of_ender',
  fireball = 'minecraft:fireball',
  fireworkRocket = 'minecraft:firework_rocket',
  llamaSpit = 'minecraft:llama_spit',
  potion = 'minecraft:potion',
  shulkerBullet = 'minecraft:shulker_bullet',
  smallFireball = 'minecraft:small_fireball',
  snowball = 'minecraft:snowball',
  spectralArrow = 'minecraft:spectral_arrow',
  trident = 'minecraft:trident',
  witherSkull = 'minecraft:wither_skull',
}
